use_frameworks!

platform :ios, '8.0'

target 'ClearentIdtechIOSFrameworkPod_Example' do
  pod 'ClearentIdtechIOSFrameworkPod', :path => '../'

  target 'ClearentIdtechIOSFrameworkPod_Tests' do
    inherit! :search_paths

    
  end
end
